title: Sudeep vision
description: Blogs about cyber security, specifically targeted attacks by advanced persistent threat (APT) groups. Solutions to CTF challenges or APT attack emulation labs are also published on this website sometimes.
remote_theme: pages-themes/hacker@v0.2.0
